In [ ]:
# Import pandas library for data manipulation
import pandas as pd

In [ ]:
# Read the CSV file
employees = pd.read_csv("employees.csv", dayfirst=True)
employees.head()

In [ ]:
# Check for duplicates
employees[employees.duplicated("employee_id")]

     employee_id employee_name Team start_date
155          NaN           NaN  NaN        NaN
156          NaN           NaN  NaN        NaN
157          NaN           NaN  NaN        NaN
158          NaN           NaN  NaN        NaN
159          NaN           NaN  NaN        NaN
..           ...           ...  ...        ...
283          NaN           NaN  NaN        NaN
284          NaN           NaN  NaN        NaN
285          NaN           NaN  NaN        NaN
286          NaN           NaN  NaN        NaN
287          NaN           NaN  NaN        NaN

[133 rows x 4 columns]

In [ ]:
# Check content of bottom 10 rows to confirm empty rows
employees.tail(10)

     employee_id employee_name Team start_date
278          NaN           NaN  NaN        NaN
279          NaN           NaN  NaN        NaN
280          NaN           NaN  NaN        NaN
281          NaN           NaN  NaN        NaN
282          NaN           NaN  NaN        NaN
283          NaN           NaN  NaN        NaN
284          NaN           NaN  NaN        NaN
285          NaN           NaN  NaN        NaN
286          NaN           NaN  NaN        NaN
287          NaN           NaN  NaN        NaN

In [ ]:
# Check to see how many rows are empty
employees.isna().all(axis=1).sum()

np.int64(134)

In [ ]:
# Remove rows where every column is null
employees = employees.dropna(how="all")

In [ ]:
# Check that duplicates were dropped
employees.shape

(154, 4)

In [ ]:
# Check the schema for datatypes
employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    float64
 1   employee_name  154 non-null    object
 2   Team           154 non-null    object
 3   start_date     154 non-null    object
dtypes: float64(1), object(3)
memory usage: 6.0+ KB

In [ ]:
# Convert employee_id to an integer
employees["employee_id"] = employees["employee_id"].astype(int)
employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    int64
 1   employee_name  154 non-null    object
 2   Team           154 non-null    object
 3   start_date     154 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.0+ KB

In [ ]:
# Parse start_date as a real date, not object
employees["start_date"] = pd.to_datetime(
    employees["start_date"],
    dayfirst=True, # (dd/mm/yyyy) format
    errors="coerce" # Valid dates are parsed, bad dates = NaT
)

employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    int64
 1   employee_name  154 non-null    object
 2   Team           154 non-null    object
 3   start_date     154 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 6.0+ KB

In [ ]:
# Save the clean CSV
employees.to_csv("clean_employees.csv", index=False)