In [1]:
# Import pandas library for data manipulation
import pandas as pd

In [2]:
# Read the CSV file
employees = pd.read_csv("employees.csv", dayfirst=True)
employees.head()

   employee_id    employee_name        team  start_date
0            1     Liam Bennett  Manchester  20/04/2026
1            2    Amelia Turner  Manchester  20/04/2026
2            3  Noah Richardson      Dublin  01/09/2025
3            4      Isla Hughes  Manchester  23/02/2026
4            5     Jack Collins      Dublin  13/10/2025

In [11]:
# Print whole dataset
employees

     employee_id    employee_name        team start_date
0              1     Liam Bennett  Manchester 2026-04-20
1              2    Amelia Turner  Manchester 2026-04-20
2              3  Noah Richardson      Dublin 2025-09-01
3              4      Isla Hughes  Manchester 2026-02-23
4              5     Jack Collins      Dublin 2025-10-13
..           ...              ...         ...        ...
149          150   Liam O'Donnell       Leeds 2025-10-01
150          151     Aoife Murphy    London 2 2025-05-12
151          152   Sean Gallagher     Bristol 2025-09-06
152          153      Niall Byrne    London 1 2025-09-01
153          154    Siobhan Walsh       Leeds 2025-10-01

[154 rows x 4 columns]

In [9]:
# Check for duplicates
employees[employees.duplicated("employee_id")]

# No duplciate employee_id entries were identifed

Empty DataFrame
Columns: [employee_id, employee_name, team, start_date]
Index: []

In [5]:
# Count rows and columns to check for expected number
employees.shape

(154, 4)

In [6]:
# Check the schema for datatypes inconsistencies
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    int64
 1   employee_name  154 non-null    object
 2   team           154 non-null    object
 3   start_date     154 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.9+ KB

In [7]:
# Parse start_date as a real date, not object
employees["start_date"] = pd.to_datetime(
    employees["start_date"],
    dayfirst=True, # (dd/mm/yyyy) format
    errors="coerce" # Valid dates are parsed, bad dates = NaT
)

In [8]:
# Re-check the data types to ensure data has been correctly parsed
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    int64
 1   employee_name  154 non-null    object
 2   team           154 non-null    object
 3   start_date     154 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 4.9+ KB

In [12]:
# Save the clean CSV
employees.to_csv("clean_employees.csv", index=False)