In [2]:
import pandas as pd

In [6]:
# Read the CSV file
employees = pd.read_csv("employees.csv", dayfirst=True)
employees.head()

   employee_id    employee_name        Team  start_date
0          1.0       Aalyan Ali  Manchester  20/04/2026
1          2.0      Daniel Rose  Manchester  20/04/2026
2          3.0      Adam  Ellis      Dublin  01/09/2025
3          4.0  Adil-Shah Nawaz  Manchester  23/02/2026
4          5.0       Alan O'Dea      Dublin  13/10/2025

In [10]:
# Check for duplicates
employees[employees.duplicated("employee_id")]

Empty DataFrame
Columns: [employee_id, employee_name, Team, start_date]
Index: []

In [8]:
# Remove rows where every column is null
employees = employees.dropna(how="all")

In [12]:
# Sanity check to validate cleaning
employees.shape

(154, 4)

In [13]:
# Check the schema for datatypes
employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    float64
 1   employee_name  154 non-null    object
 2   Team           154 non-null    object
 3   start_date     154 non-null    object
dtypes: float64(1), object(3)
memory usage: 6.0+ KB

In [14]:
# Convert employee_id to an integer
employees["employee_id"] = employees["employee_id"].astype(int)
employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    int64
 1   employee_name  154 non-null    object
 2   Team           154 non-null    object
 3   start_date     154 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.0+ KB

In [15]:
# Parse start_date as a real date, not object
employees["start_date"] = pd.to_datetime(
    employees["start_date"],
    dayfirst=True, # (dd/mm/yyyy) format
    errors="coerce" # Valid dates are parsed, bad dates = NaT
)

employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154 entries, 0 to 153
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    154 non-null    int64
 1   employee_name  154 non-null    object
 2   Team           154 non-null    object
 3   start_date     154 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 6.0+ KB

In [16]:
# Save the clean CSV
employees.to_csv("clean_employees.csv", index=False)